language: ruby

cache:
  bundler: true
  yarn: true

rvm:
  - 2.5.3
  - 2.6.0-preview3

gemfile:
  - Gemfile

bundler_args: ""

before_script:
  - bundle exec licensed cache

script:
  - bundle exec bundle-audit check -qu
  - bundle exec licensed status
  - bundle exec rubocop -f s -DPR --color
